name = "Concatenation"
author = "Mitemi"
version = "1.1.0-1"
pack-format = "packwiz:1.1.0"

[metadata]

base_url = "https://raw.githubusercontent.com/warcow-war/minecraftmodpacktinklecow/main/"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8d2465c77d22d81da52fbcf766202eabb95306bfe527f60dc22a588d2413f4a"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
